/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as WeeklyPlanRouteImport } from './routes/weekly-plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyPlanRoute = WeeklyPlanRouteImport.update({
  id: '/weekly-plan',
  path: '/weekly-plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/requests': typeof RequestsRoute
  '/weekly-plan': typeof WeeklyPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/requests': typeof RequestsRoute
  '/weekly-plan': typeof WeeklyPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/requests': typeof RequestsRoute
  '/weekly-plan': typeof WeeklyPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/requests' | '/weekly-plan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/requests' | '/weekly-plan'
  id: '__root__' | '/' | '/requests' | '/weekly-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RequestsRoute: typeof RequestsRoute
  WeeklyPlanRoute: typeof WeeklyPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly-plan': {
      id: '/weekly-plan'
      path: '/weekly-plan'
      fullPath: '/weekly-plan'
      preLoaderRoute: typeof WeeklyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RequestsRoute: RequestsRoute,
  WeeklyPlanRoute: WeeklyPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
